### ISSUE TITLE
CastException when updateing time series item

### ISSUE THREAD

**Issue by matiashf-cognite** [cognitedata/cdp-spark-datasource#210] opened 2019-03-26 16:04 UTC
I'm trying to copy timeseries (metadata, not datapoints) between tenants in [a databricks notebook](https://westeurope.azuredatabricks.net/?o=2323107922886870#notebook/2077042838583310)

```
spark.read.format("com.cognite.spark.datasource").option("type", "timeseries").option("apiKey", dbutils.secrets.get("matiashf", "akerbp")).load().createTempView('timeseries_production')
spark.read.format("com.cognite.spark.datasource").option("type", "timeseries").option("apiKey", dbutils.secrets.get("matiashf", "matiashf")).load().createTempView('timeseries_testing')
```

```
%sql
insert into timeseries_testing select * from timeseries_production
```

When I execute, I get the following error message:
```
Error in SQL statement: SparkException: Job aborted due to stage failure: Task 5 in stage 21.0 failed 4 times, most recent failure: Lost task 5.3 in stage 21.0 (TID 985, 10.139.64.13, executor 8): java.lang.ClassCastException: scala.collection.mutable.WrappedArray$ofRef cannot be cast to scala.collection.immutable.Vector
	at com.cognite.spark.datasource.UpdateTimeSeriesItem$$anonfun$apply$2.apply(TimeSeriesRelation.scala:65)
	at scala.Option.map(Option.scala:146)
	at com.cognite.spark.datasource.UpdateTimeSeriesItem$.apply(TimeSeriesRelation.scala:65)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$7.apply(TimeSeriesRelation.scala:93)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$7.apply(TimeSeriesRelation.scala:93)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at com.cognite.spark.datasource.TimeSeriesRelation.com$cognite$spark$datasource$TimeSeriesRelation$$updateOrPostTimeSeries(TimeSeriesRelation.scala:93)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$insert$1$$anonfun$apply$3.apply(TimeSeriesRelation.scala:88)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$insert$1$$anonfun$apply$3.apply(TimeSeriesRelation.scala:88)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at cats.instances.VectorInstances$$anon$1$$anonfun$traverse$2.apply(vector.scala:78)
	at cats.instances.VectorInstances$$anon$1$$anonfun$traverse$2.apply(vector.scala:77)
	at cats.instances.VectorInstances$$anon$1.cats$instances$VectorInstances$class$$anon$$loop$2(vector.scala:41)
	at cats.instances.VectorInstances$$anon$1$$anonfun$foldRight$1.apply(vector.scala:42)
	at cats.instances.VectorInstances$$anon$1$$anonfun$foldRight$1.apply(vector.scala:42)
	at cats.Eval$.advance(Eval.scala:272)
	at cats.Eval$.loop$1(Eval.scala:354)
	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
	at cats.Eval$Defer.value(Eval.scala:258)
	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:79)
	at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:13)
	at cats.Parallel$.parTraverse(Parallel.scala:132)
	at cats.syntax.ParallelTraversableOps$.parTraverse$extension(parallel.scala:36)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$insert$1.apply(TimeSeriesRelation.scala:88)
	at com.cognite.spark.datasource.TimeSeriesRelation$$anonfun$insert$1.apply(TimeSeriesRelation.scala:80)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:951)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2293)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2293)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:139)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$13.apply(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1432)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:503)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
```

**Comment by matiashf-cognite** [comment] 2019-03-26 16:11
I actually got the error in [a different notebook](https://westeurope.azuredatabricks.net/?o=2323107922886870#notebook/2077042838582603/command/2077042838583254) than the [one I linked to above](https://westeurope.azuredatabricks.net/?o=2323107922886870#notebook/2077042838582603/command/2077042838583254), and now I have difficulties replicating the error message. Instead I get another error. Notice how the same ID is repeated again and again:
```
Error in SQL statement: SparkException: Job aborted due to stage failure: Task 2 in stage 57.0 failed 4 times, most recent failure: Lost task 2.3 in stage 57.0 (TID 2403, 10.139.64.13, executor 8): com.cognite.spark.datasource.CdpApiException: Request to https://api.cognitedata.com/api/0.5/projects/matiashf/timeseries failed with status 400: Invalid asset ids: 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451, 2957519993315451
	at com.cognite.spark.datasource.CdpConnector$class.parseCdpApiError(CdpConnector.scala:96)
	at com.cognite.spark.datasource.TimeSeriesRelation.parseCdpApiError(TimeSeriesRelation.scala:71)
	at com.cognite.spark.datasource.CdpConnector$$anonfun$defaultHandling$1.applyOrElse(CdpConnector.scala:102)
	at com.cognite.spark.datasource.CdpConnector$$anonfun$defaultHandling$1.applyOrElse(CdpConnector.scala:100)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at scala.collection.AbstractMap.applyOrElse(Map.scala:59)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:137)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:127)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.cats$effect$internals$TrampolineEC$JVMTrampoline$$super$startLoop(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply$mcV$sp(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at cats.effect.internals.TrampolineEC$JVMTrampoline$$anonfun$startLoop$1.apply(TrampolineEC.scala:93)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:92)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:133)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:120)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anonfun$send$1.com$softwaremill$sttp$asynchttpclient$AsyncHttpClientBackend$$anonfun$$success$1(AsyncHttpClientBackend.scala:45)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anonfun$send$1$$anonfun$apply$3.apply(AsyncHttpClientBackend.scala:55)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anonfun$send$1$$anonfun$apply$3.apply(AsyncHttpClientBackend.scala:55)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anon$1.onCompleted(AsyncHttpClientBackend.scala:75)
	at com.softwaremill.sttp.asynchttpclient.AsyncHttpClientBackend$$anon$1.onCompleted(AsyncHttpClientBackend.scala:73)
	at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:66)
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:223)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:258)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:113)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:142)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by wjoel** [comment] 2019-03-27 07:38
Thanks for reporting this! I've been able to reproduce both errors in additional tests that I've added. The second one is surprising.

**Comment by matiashf-cognite** [comment] 2019-03-27 08:07
The asset id error might be caused by me trying to copy references to non-existing assets, because no assets exist in the tenant I'm copying to. :see_no_evil:

**Comment by matiashf-cognite** [comment] 2019-03-27 09:39
![](https://github.trello.services/images/mini-trello-icon.png) [Create types for time series in CDP](https://trello.com/c/XnvxS1DS/153-create-types-for-time-series-in-cdp)

**Comment by wjoel** [comment] 2019-03-27 10:10
Yes, the asset ids thing has a funny error message (which could be improved on the API side by removing duplicates) but it makes sense.

Note that this is a public repository, so it's better to not post links to internal resources but if you do, be careful so you don't post sensitive information about customers etc. No such issues here so no worries, just wanted to mention it. :)

**Comment by wjoel** [comment] 2019-03-27 11:59
@matiashf-cognite I have a fix for this in https://github.com/cognitedata/cdp-spark-datasource/pull/211 but in your case, you can use `insert into timeseries_testing select name, isString, metadata, unit, assetId, isStep, description, null as securityCategories, id, createdTime, lastUpdatedTime from timeseries_production` as a workaround, setting securityCategories to null (since you don't have any in your destination project). Might also need to change the assetId as well, of course.

**Comment by wjoel** [comment] 2019-03-27 14:20
Fixed by https://github.com/cognitedata/cdp-spark-datasource/pull/211 and I've made commits to cognite-tsdb to remove duplicates from the error messages.

**Closed** 2019-04-08 17:55 UTC
